#!/bin/sh

# Define the location of the configuration file
config_file="$HOME/.config/lsm/config"

# Check if the configuration file exists and source it
if [ -f "$config_file" ]; then
  . "$config_file"
else
  echo "Configuration file not found. Please create one at $config_file."
  exit 1
fi

# Define function to convert color names to ANSI escape codes
get_color_code() {
  case "$1" in
    blue) echo "\033[1;34m" ;;
    orange) echo "\033[0;33m" ;;
    pink) echo "\033[1;35m" ;;
    magenta) echo "\033[1;35m" ;;
    green) echo "\033[1;32m" ;;
    red) echo "\033[1;31m" ;;
    yellow) echo "\033[1;33m" ;;
    cyan) echo "\033[1;36m" ;;
    white) echo "\033[1;37m" ;;
    gray) echo "\033[1;30m" ;;
    mauve) echo -e "\033[38;2;198;160;246m" ;;
    rosewater) echo -e "\033[38;2;244;219;214m" ;;
    flamingo) echo -e "\033[38;2;240;198;198m" ;;
    lavender) echo -e "\033[38;2;183;189;248m" ;;
    navy) echo -e "\033[38;2;10;25;47m" ;;
    light_gray) echo -e "\033[38;2;248;248;248m" ;;
    teal) echo -e "\033[38;2;0;180;138m" ;;
    light_teal) echo -e "\033[38;2;0;209;160m" ;;
    fresh_green) echo -e "\033[38;2;166;218;149m" ;;
    catppuccin_mocha) echo -e "\033[38;2;75;65;82m" ;;
    catppuccin_frappe) echo -e "\033[38;2;194;164;148m" ;;
    catppuccin_macchiato) echo -e "\033[38;2;157;121;92m" ;;
    catppuccin_latte) echo -e "\033[38;2;214;210;196m" ;;
    pastel_pink) echo -e "\033[38;2;237;179;199m" ;;
    pastel_yellow) echo -e "\033[38;2;243;243;188m" ;;
    pale_blue) echo -e "\033[38;2;156;197;227m" ;;
    pale_green) echo -e "\033[38;2;189;233;190m" ;;
    pale_purple) echo -e "\033[38;2;177;156;217m" ;;
    black) echo -e "\033[38;2;40;40;40m" ;;
    red) echo -e "\033[38;2;204;102;102m" ;;
    green) echo -e "\033[38;2;102;204;102m" ;;
    yellow) echo -e "\033[38;2;204;204;102m" ;;
    blue) echo -e "\033[38;2;102;102;204m" ;;
    magenta) echo -e "\033[38;2;204;102;204m" ;;
    cyan) echo -e "\033[38;2;102;204;204m" ;;
    white) echo -e "\033[38;2;204;204;204m" ;;
    gray) echo -e "\033[38;2;102;102;102m" ;;
    *) echo "\033[0m" ;;  # Default no color
  esac
}


# Fetch color codes based on configuration
color_folder=$(get_color_code "$Color_Folder")
color_file=$(get_color_code "$Color_File")

# Set the default directory to list if no argument is provided
if [ $# -eq 0 ]; then
  set -- "."  # Set default argument to the current directory
fi

# Display directory contents with detailed listing like ls -l
for dir in "$@"; do
  if [ -d "$dir" ]; then
    echo -e "$(date +"%Y-%m-%d %H:%M:%S") $(whoami) $dir"
    # List files and directories with coloring, include hidden if Show_Dots is true
    if [ "$Show_Dots" = "true" ]; then
      file_pattern=".* *"
    else
      file_pattern="*"
    fi

    # Check if the directory is not empty
    shopt -s nullglob dotglob
    items=($dir/$file_pattern)
    shopt -u nullglob dotglob

    if [ ${#items[@]} -eq 0 ]; then
      echo "No files in $dir"
    else
      for item in "${items[@]}"; do
        if [ -d "$item" ]; then
          ls -ldh "${item}" | awk -v color="$color_folder" '{ printf "%s %s %s %s %s %s %s %s ", $1, $2, $3, $4, $5, $6, $7, $8; printf color "%s\033[0m\n", $9 }'
        else
          ls -ldh "${item}" | awk -v color="$color_file" '{ printf "%s %s %s %s %s %s %s %s ", $1, $2, $3, $4, $5, $6, $7, $8; printf color "%s\033[0m\n", $9 }'
        fi
      done
    fi
  else
    echo "$dir is not a directory"
  fi
done

